services:
  selenium-grid:
    build:
      context: .
      dockerfile: Dockerfile
      target: selenium_grid
    image: autojav-selenium
    container_name: selenium-grid
    restart: unless-stopped
    shm_size: '2g'
    environment:
      - SE_NODE_SESSION_TIMEOUT=600
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - av-network

  av-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: autojav-runtime
    container_name: av-metadata-api
    restart: unless-stopped
    depends_on:
      - selenium-grid
    command: ["python", "-m", "src.api_server"]
    ports:
      - "${API_PORT:-5555}:5555"
    volumes:
      - ${SOURCE_DIR:-./source}:/app/source
      - ${TARGET_DIR:-./organized}:/app/target
      - ${CONFIG_DIR:-./config}:/app/config
      - ${LOGS_DIR:-./logs}:/app/logs
      - chrome_data:/app/.chrome-data
    environment:
      - CONFIG_FILE=/app/config/config.yaml
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TZ=${TZ:-Asia/Shanghai}
      - SELENIUM_HUB_URL=http://selenium-grid:4444/wd/hub
      - MAX_CONCURRENT_FILES=${MAX_CONCURRENT_FILES:-2}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-2}
      - MAX_CONCURRENT_DOWNLOADS=${MAX_CONCURRENT_DOWNLOADS:-2}
      - SAFE_MODE=${SAFE_MODE:-false}
      - DOWNLOAD_IMAGES=${DOWNLOAD_IMAGES:-true}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
    networks:
      - av-network

  av-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: autojav-runtime
    container_name: av-metadata-web
    restart: unless-stopped
    depends_on:
      - av-api
    command: ["python", "web_app.py"]
    ports:
      - "${WEB_PORT:-8080}:8080"
    volumes:
      - ${SOURCE_DIR:-./source}:/app/source
      - ${TARGET_DIR:-./organized}:/app/target
      - ${CONFIG_DIR:-./config}:/app/config
      - ${LOGS_DIR:-./logs}:/app/logs
    environment:
      - API_HOST=av-api
      - API_PORT=5555
      - WEB_PORT=8080
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - av-network

volumes:
  chrome_data:
    driver: local

networks:
  av-network:
    driver: bridge