version: '3.8'

services:
  # Web界面服务
  av-scraper-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: av-scraper-web
    restart: unless-stopped
    
    ports:
      - "${WEB_PORT:-5000}:5000"
    
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TZ=${TZ:-Asia/Shanghai}
    
    volumes:
      # 配置目录
      - ${CONFIG_DIR:-./config}:/app/config
      # 日志目录
      - ${LOGS_DIR:-./logs}:/app/logs
      # 源文件目录（只读）
      - ${SOURCE_DIR:-./source}:/app/source:ro
      # 目标目录
      - ${TARGET_DIR:-./organized}:/app/organized
      # 代码挂载（开发模式）
      - ./web:/app/web:ro
      - ./src:/app/src:ro
    
    networks:
      - av-scraper-network
    
    depends_on:
      - av-scraper
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 主刮削服务（继承自原始docker-compose.yml）
  av-scraper:
    extends:
      file: docker-compose.yml
      service: av-scraper
    # 移除端口映射，因为不需要直接访问
    ports: []

# 使用原始网络
networks:
  av-scraper-network:
    external: true