version: '3.8'

services:
  # Selenium Grid 服务
  selenium-grid:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium-grid-standalone
    restart: unless-stopped
    ports:
      - "4445:4444"  # 映射到4445避免端口冲突
      - "7900:7900"  # noVNC web viewer
      - "5900:5900"  # VNC server
    environment:
      - SE_NODE_SESSION_TIMEOUT=600
    shm_size: '2g'
    networks:
      - autojav-network

  # 主刮削服务 (从Docker Hub拉取)
  av-scraper:
    image: yaolidong/autojav-scraper:latest  # 从Docker Hub拉取
    container_name: av-metadata-scraper
    restart: unless-stopped
    
    ports:
      - "5555:5555"
    
    volumes:
      - ./source:/app/source:ro
      - ./target:/app/target
      - ./config:/app/config
      - ./logs:/app/logs
    
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
      - API_HOST=0.0.0.0
      - API_PORT=5555
      - SELENIUM_HUB_URL=http://selenium-grid:4444/wd/hub
      - WEB_HOST=av-scraper-web
      - WEB_PORT=8899
    
    networks:
      - autojav-network
    
    depends_on:
      - selenium-grid
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 90s

  # Web界面服务 (从Docker Hub拉取)
  av-scraper-web:
    image: yaolidong/autojav-web:latest  # 从Docker Hub拉取
    container_name: av-scraper-web
    restart: unless-stopped
    
    ports:
      - "8899:8899"
    
    volumes:
      - ./source:/app/source:ro
      - ./target:/app/target:ro
      - ./config:/app/config
      - ./logs:/app/logs:ro
    
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
      - API_HOST=av-scraper
      - API_PORT=5555
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8899
    
    networks:
      - autojav-network
    
    depends_on:
      - av-scraper
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8899/"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s

networks:
  autojav-network:
    driver: bridge