# Basic Configuration Example
# This is a minimal configuration for getting started with AV Metadata Scraper

# Directory Settings (REQUIRED)
directories:
  source: "/path/to/your/video/files"      # Change this to your video directory
  target: "/path/to/organized/output"      # Change this to your output directory

# Scraper Settings
scraping:
  priority: ["javdb", "javlibrary"]        # Try JavDB first, then JavLibrary
  max_concurrent_files: 2                  # Process 2 files at once (safe default)
  retry_attempts: 3                        # Retry failed operations 3 times
  timeout: 30                              # 30 second timeout for requests

# File Organization
organization:
  naming_pattern: "{actress}/{code}/{code}.{ext}"  # Organize by actress/code
  download_images: true                    # Download cover images
  save_metadata: true                      # Save metadata as JSON files

# Browser Settings
browser:
  headless: true                           # Run browser in background
  timeout: 30                              # Browser operation timeout

# Logging
logging:
  level: "INFO"                            # Log level (DEBUG, INFO, WARNING, ERROR)

# Supported Video Extensions
supported_extensions:
  - ".mp4"
  - ".mkv"
  - ".avi"
  - ".wmv"
  - ".mov"