# JAVDB Configuration
javdb:
  username: ""
  password: ""
  cookies_file: "config/javdb_cookies.json"
  login_retry_attempts: 3
  login_retry_delay: 60

# Directory Configuration
directories:
  source: "./source"
  target: "./target"
  config: "./config"
  logs: "./logs"

# Network Configuration
network:
  proxy_url: "http://192.168.3.2:6152"

# Processing Configuration
processing:
  max_concurrent_files: 2
  max_concurrent_requests: 2
  max_concurrent_downloads: 2
  create_metadata_files: true
  download_images: true
  resize_images: false
  create_thumbnails: false

# API Configuration
api:
  host: "0.0.0.0"
  port: 5555
  debug: false

# Web Configuration
web:
  host: "0.0.0.0"
  port: 8899
  debug: true

# Scraper configuration
scrapers:
  javdb:
    base_url: "https://javdb563.com"
